### ISSUE TITLE
Line numbering not working correctly for g-code

### ISSUE THREAD

**Issue by M4X1K02** [jmzambon/libreoffice-code-highlighter#15]
The line numbering feature for g-code does not add additional spaces between letters and it also does not color the line numbers in grey properly:
![Screenshot 2022-08-10 085416](https://user-images.githubusercontent.com/91785448/183835015-41f2ed23-2dde-4dc3-91a4-777aa4b2f1ed.png)

**Comment by jmzambon** [comment]
Hi,
Thanks for reporting this. I'll have a look today.

**Comment by jmzambon** [comment]
So other weird behaviour here: with line numbering on, line numbers and separator are correctly inserted, but highlighting is messed up.

I think the problem come from the g-code Pygments lexer, that did not recognize number token properly...

**Comment by M4X1K02** [comment]
Hi,
so it's nothing you or I can fix right now?

**Comment by jmzambon** [comment]
I need to rethink the line numbering. I hope this can be done quickly.

**Comment by jmzambon** [comment]
This is fixed in the last release (2.4.0).
Please check for update in the LibreOffice extension manager.

**Comment by M4X1K02** [comment]
Can confirm it works now.
Thank you for your time and effort! 👍
