### ISSUE TITLE
pygments release

### ISSUE THREAD

**Issue by flywire** [jmzambon/libreoffice-code-highlighter#16]
fyi https://github.com/pygments/pygments/releases/tag/2.13.0

> Updated lexers:
> StarOffice Basic (https://github.com/pygments/pygments/pull/2170)
> 
> Added styles:

> StarOffice (https://github.com/pygments/pygments/pull/2168)

**Comment by jmzambon** [comment]
Hi,

Thanks, I know this.
But what is the issue exactly?
