### ISSUE TITLE
Use Character styles instead of Direct styles

### ISSUE THREAD

**Issue by sdasda7777** [jmzambon/libreoffice-code-highlighter#19]
Hey, would it be possible to modify the code to use Character styles instead of Direct styles?

I believe when using Direct styles and saving to .fodt, all Direct styles are assigned random unique names, which makes it much harder to properly version with git, whereas all usages of a Character style use the same name.

**Comment by jmzambon** [comment]
Hi, sorry to answer so late, I didn't receive any notification of your post.
What if you check the option "Use character styles in Writer" from de [dialog](https://github.com/jmzambon/libreoffice-code-highlighter/raw/master/screenshots/code-highlighter-dialog.png?raw=true)?

**Comment by sdasda7777** [comment]
Ah, you're right, I completely missed that. Amazing, thanks!

**Comment by flywire** [comment]
See also #5 #8
