### ISSUE TITLE
Add some kind of preview, perhaps even custom color selection

### ISSUE THREAD

**Issue by sdasda7777** [jmzambon/libreoffice-code-highlighter#20]
Would it be possible to show preview of the Highlight Style (colors, mainly) somewhere? (There is noticeable empty space on the right)

I assume I must not be the only one who has no clue what the difference between `borland`, `lovelace` and `vim` is, and just going through all the styles until I find one that is not terrible seems like uneffective usage of my time.

Having an option to modify the styles would be nice too, actually, since the style may be almost perfect, but perhaps might look nicer with strings highlighted in different color, or what have you.

![image](https://user-images.githubusercontent.com/17746796/213142599-8b9eb8a5-9aac-4d8e-a3a4-538bc85c86c5.png)

**Comment by jmzambon** [comment]
Hi,
This could be an interesting enhancement. But I need to think about it: a solution is not obvious, and probably not easy to implement...
Meanwhile you can have a look here: https://pygments.org/styles.

**Comment by sdasda7777** [comment]
> Meanwhile you can have a look here: https://pygments.org/styles.

I see, that's definitely helpful, thanks. Adding this link to the main page and possibly to the extension somehow would be a big improvement, but I still think it would be better to be able to use the extension fully without having to reference an external site.

**Comment by jmzambon** [comment]
Hi,

I've finally found a solution and implemented an in-document preview. Please see the last release (v2.5.0).
