### ISSUE TITLE
Line numbers zero padding

### ISSUE THREAD

**Issue by sdasda7777** [jmzambon/libreoffice-code-highlighter#21]
Hi, would it be possible to add a feature to pad line numbers with zeroes?

I think either to fixed number of digits or dynamically to the largest number of digits used would be fine, but the possibility of choosing between these two would be absolutely perfect.

**Comment by jmzambon** [comment]
Hi,

Thank for suggesting. I'll have a look on this.

**Comment by jmzambon** [comment]
Could you try the last uploaded [codehighlighter2.oxt](https://github.com/jmzambon/libreoffice-code-highlighter/blob/master/codehighlighter2.oxt)?
You'll have to input 0 in the new 'Padding symbol' option (button [More...] of the dialog box).
Thanks.

**Comment by sdasda7777** [comment]
Hey, it works great, but I had trouble finding it in the settings to be honest 😅
Could you maybe change the label to say "Line number padding", or something like that? 😄

**Comment by jmzambon** [comment]
The line numbering options use to exist before your demand. I've just added the adding symbol option. So the section is not only concerned with number padding.

**Comment by sdasda7777** [comment]
I'm not sure I understand. Can you explain what else it does except for the line number padding?

**Comment by jmzambon** [comment]
The "line numbering" section of the options tab allows to:
- choose starting number ("Start at" item);
- modify the size of numbers, in percent of the code size ("Height (%)" item);
- add separator characters after line number  ("Separator" item);
- define the number padding symbol, most of the time nothing or 0 ("Padding symbol" item).

**Comment by sdasda7777** [comment]
I see, yes 😅 I was just trying to point out that it wasn't completely clear to me that "Padding symbol" means the line number padding symbol, even though I knew the feature is there (which most people won't know), so some rewording of the label might be possible to clear this up 😅

**Comment by jmzambon** [comment]
The option lays in the section "Line numbering", so it was obvious to me. I'll think about a better name, ideally no too long... :-)
