### ISSUE TITLE
Trouble with highlighting Julia Code, possibly due to unicode characters

### ISSUE THREAD

**Issue by reumle** [jmzambon/libreoffice-code-highlighter#22]
Hi, I am trying to include some Juia Code on an Impress document. A first (julia) function works  fine, but for the next one (shown below), highlighting is all over the  place, and some (unicode) characters get mangled, like the italic t and the italic ig.
````julia 
function Projection(tax_rate, 
  tax_credit_0,
  cap_mkt::CapMvkt,
  invs::InvPort,
  liabs::LiabIns,
  liabs_other::LiabOther,
  dyn::Dynamic)
  ##                                      1. intialisation   
  proj = Projection(liabs, tax_rate, tax_credit_0)
  ##                                      2. boucle sur les années jusque horizon des passifs

  for 𝑡 ∈ 1:liabs.dur
  ##                                      2.1 boucle dumy sur les couts fixes
    for 𝑖𝑔 ∈ [:IGCash, :IGStock,:IGBond1]
      proj.fixed_cost_gc[𝑡] +=
      invs.igs[𝑖𝑔].cost.abs[𝑡] *
      invs.igs[𝑖𝑔].cost.cum_infl_abs[𝑡] *
      liabs.gc[𝑡]
    end
  end
  ##     


  ##                                      3. traitement des dettes, going oncern etc
  l_other = deepcopy(liabs_other)         # 3.1 les dettes sub.
  goingconcern!(l_other, liabs.Δgc)       # 3.2 modifie l_other.sub,tq la dette s'mortisse en ligne avec liabs.gc
  ##                                      4. initialisation - fin
  val0!(cap_mkt, invs, liabs, l_other, proj) # 5 val0! intialise tpg par itération sur les mp,puis dettes l_other
                                             # et invest(la valeur) et le surplus ie différence
  proj.cf[:,:gc] = liabs.Δgc * (proj.val_0[1,:invest] -    # 6.initialisation proj.cf[:,:gc] avec valeur en [1]
                  proj.val_0[1,:tpg] -
                  proj.val_0[1,:l_other])
  ##     ---------------------            7. la vraie boucle de projection du bilan
  for 𝑡 = 1:liabs.dur
    project_bs!(𝑡, cap_mkt, invs, liabs, l_other, dyn, proj) # 8 appelé une fois par année de projection ici p2.
  end
  ##     ---------------------            7. fin
  ##                                      9. post traitement de partage avec les assurés. 
  valbonus!(cap_mkt.rfr.x, proj)          # 10 MAJ du champ (prov pour) bonus  des dataframes p.val, p.val_0
  valcostprov!(cap_mkt.rfr.x, invs, proj) # 11 MAJ du champ cost_prov des dataframes proj.cf , p.val, p.val_0
  return proj
end
                      
```

For the curious, the code is coming from this site https://github.com/mkriele/ValueOrientedRiskManagementInsurance.jl

And thank you for the extension!

**Comment by jmzambon** [comment]
Hi,

Thank you for sharing the issue.
This one is quite odd: it happens only with Text Box or Text Shape, while highlighting works fine for plain text, text frame and table cell (in Writer thus). It sounds like text box api were somehow broken. I'll try to narrow the problem as soon as possible.
In the meanwhile, if you don't have too much snippets to highlight, you can workaround the issue by formatting them in Writer and copy-paste to Impress.

**Comment by jmzambon** [comment]
Hi,

Could you please have a look at the [last uploaded version](https://github.com/jmzambon/libreoffice-code-highlighter/raw/master/codehighlighter2.oxt)?
The problem was: for an unknown reason, unicode character over 0x10000, from within a text shape (which is used in Impress for displaying text), is seen as a double character (instead of being "length transparent"), which causes offset highlightings. This is probably a bug in LibreOffice, as all works fine in any other context (plain text in Writer, text frame and table cell). 

**Edit**
The same problem occured in Calc cells. Last version also fixes it.

**Comment by reumle** [comment]
Hello! sorry for the long delay,! 
I just relogged to my github account, and was reminded that this issue was my last activity, back in may. So I came here, installed the new version of code highlighter, and it **works perfectly**. 
Bravo and thank you so much!

**Comment by jmzambon** [comment]
Thank you for the feedback!
