### ISSUE TITLE
Input fields not visible with dark theme

### ISSUE THREAD

**Issue by sdasda7777** [jmzambon/libreoffice-code-highlighter#24]
Hey, I noticed that the input fields aren't really visible when dark theme is enabled (I believe the theme is taken from OS by default, so this might affect quite a few people).

I think adding white edges to the fields would fix this:

![image](https://github.com/jmzambon/libreoffice-code-highlighter/assets/17746796/e52b6b1a-e2e5-40fb-923c-4ef03f61e8b1)

I can see the fields are visible with light mode, though (dark) edges for them would help here too, imo:

![image](https://github.com/jmzambon/libreoffice-code-highlighter/assets/17746796/35210f7a-8cf2-4d04-95e4-d6f8b17af879)

**Comment by jmzambon** [comment]
I'll have a look.

**Comment by jmzambon** [comment]
I've patched the dialog box. Could you test the [last uploaded version](https://github.com/jmzambon/libreoffice-code-highlighter/raw/a37a57d508dcfd0b297fdc74f485e7c64bbf241b/codehighlighter2.oxt)?

**Comment by sdasda7777** [comment]
That works great, thanks!
