### ISSUE TITLE
clicking on highlight menu item does nothing

### ISSUE THREAD

**Issue by alien999999999** [jmzambon/libreoffice-code-highlighter#25]
I thought, maybe i needed that python script provider thing, but i couldn't find anything on my Mageia distro, and no information on what kind of files would be installed, if i had this or not.
I figured, i just find a verbose log option and see what happens, but libreoffice seems to fork after startup and logs seem to be disabled when compiling it...

Please help me, is there really no log to just see what happens when i click the hightlight menu item? and what kind of files/plugins/libraries should i have if that python provider thing is installed?

**Comment by alien999999999** [comment]
![highlight-error](https://github.com/jmzambon/libreoffice-code-highlighter/assets/3256762/0aaf6cba-5b6c-4134-ab3b-8eb2c6c2a89f)
if i try the hightlighter v1, i get python errors, so i'm guessing i have this python provider thing?

**Comment by alien999999999** [comment]
ok, weird, after trying v1, i re-installed v2 in order to check some debug stuff, but it worked?

annoying thought that for php code, i do need to preface with <?php and if the code selection is until the end, i have no way to cancel that, or put regular text after it?

**Comment by jmzambon** [comment]
Hi,

Code Highlighter v1 is no more supported by is creator.
In some linux distros, the python script provider is installed with LibreOffice. So if the extension works you don"t have to worry about that.
~~For what remains of your last message, I really don"t understand what is your issue. Can you give a sample code , explain what options are selected and detail how it fails? Thanks.~~ (see next comments)

You can enable extension logging here: Tools -> Options -> LibreOffice -> Advanced -> Open Expert Configuration -> ooo.ext.code-highlighter.Registry and set LogLevel to 2. Then launch LibO from console and see the output.

**Comment by jmzambon** [comment]
> annoying thought that for php code, i do need to preface with <?php

I test this and, yes, you need the two first '<?' characters. This is a Pygments php lexer feature, see here : https://pygments.org/demo.
You may ask for an enhancement on the [Pygments github site](https://github.com/pygments/pygments).

**Comment by alien999999999** [comment]
As a test, i wrote some random lines at the end of the document, selected it, and set to PHP highlighting.
Then, i wanted to write some normal text after this... but i couldn't click after it, or use arrow keys to get back to normal...

then, i wanted to cancel the highlighting, but there is no such option?

I ended up just "undo" -ing until it was gone, and then first made some empty lines at the end, before i redid the highlighting.

Is there no easy way to cancel the highlighting, or enter regular text after it?

**Comment by jmzambon** [comment]
> annoying thought that [...] if the code selection is until the end, i have no way to cancel that, or put regular text after it?

See here: https://github.com/jmzambon/libreoffice-code-highlighter#general-behaviour.
If you highlight code in plain text, be sure to add at least an empty paragraph after the code. Best choice is to put code in text frame.

> Is there no easy way to cancel the highlighting, or enter regular text after it?

Writer global features will do it:
- if you used character styles, just apply the default style;
- otherwise try CTRL+M, that remove direct formatting from selected text.
