### ISSUE TITLE
go lang string don't detection

### ISSUE THREAD

**Issue by srfirouzi** [jmzambon/libreoffice-code-highlighter#26]
Hello
I am using code highlighter for golang, but string doesn't detect
Golang has two types of strings

1. use backticks (`) for definition
2. use double quotes ("") for definition

now string by backticks detection, but by double quotes don't detection

**Comment by jmzambon** [comment]
Hi,

Thank you for the report.
I'm not sure to understand what's wrong. Do you have any code snippet showing the defect?
Could you also try the [Pygments demo](https://pygments.org/demo/) to  check if the problem isn't in the original lexer?

**Comment by srfirouzi** [comment]
this a sample of code
![Screenshot from 2023-09-03 22-17-21](https://github.com/jmzambon/libreoffice-code-highlighter/assets/42442361/918826f0-ce1c-44db-8237-9cd4494c7789)

double quotes string like python string

**Comment by jmzambon** [comment]
Hi,

You are using typographic double quotes (“...”), which are not recognized by the Pygments lexer as normal double quotes ("...").
When typing code, either do ctrl-Z after entering each quote or, more simply, define language as None for your snippet (menu _Tools -> Language -> Selection_ or _Paragraph_). Still better: use a dedicated paragraph style for your code snippet, with language set as none (and monospace font for example).
Have a nice evening.

![image](https://github.com/jmzambon/libreoffice-code-highlighter/assets/29238674/01239a7b-d32d-4229-8014-de99f10ad250)

**Comment by srfirouzi** [comment]
Thank,
it worked
