### ISSUE TITLE
Highlighting LLVM code removes some numeric labels

### ISSUE THREAD

**Issue by BirdLogics** [jmzambon/libreoffice-code-highlighter#27]
When I try to highlight LLVM code, numeric labels which are followed by a same line comment are removed. This is problematic since a lot of generated LLVM code I've seen uses numeric labels and has comments to give the predecessor blocks.

Example:
```llvm
define i32 @foobar(i32 %0) {
; this label is fine
start:
%1 = icmp eq i32 %1, i32 0
br i1 icmp, label %exit, label %10

; this label disappears
10: ; if a comment is here
%2 = add i32 %1, i32 1
br label %exit

; this label is fine
exit: ; even if a comment is here
%3 = phi i32 [ %1, %start ], [ %2, %10 ]
ret i32 %3
}
```
Or more realistically:
```llvm
33:                                               ; preds = %147, %4
  %34 = load i32, ptr %7, align 4
  %35 = icmp sgt i32 %34, 0
  br i1 %35, label %36, label %150
```
![image](https://github.com/jmzambon/libreoffice-code-highlighter/assets/47367734/87dd1260-2aea-469f-94ea-a2cf7e20e7cd)

**Comment by BirdLogics** [comment]
This might actually be related to https://github.com/pygments/pygments/issues/1874. My current version of Code Highlighter 2 is 2.5.6. It looks like pygments was recently updated, so this issue might be fixed already.

 If I highlight the code with pygments 2.14.0, the version installed on my system, it highlights the code correctly.

**Comment by jmzambon** [comment]
Hi,

Thank you for sharing the issue.
I'm quite sure it is indeed a Code Highlighter 2 problem: the extension tries to remove any existing line numbering when the option is unchecked.
I'll have a look as soon as possible.

**Comment by jmzambon** [comment]
Hi,
Waiting for a better solution, I've pushed a new version including a simple test on LLVM lexer. This should fix your issue.
Please keep me informed.
