### ISSUE TITLE
using empty exception is bad practice.

### ISSUE THREAD

**Issue by baseplate-admin** [jmzambon/libreoffice-code-highlighter#28]
Hi,

Maybe you can explain here

https://github.com/jmzambon/libreoffice-code-highlighter/blob/7db2b304c653246c28f74a3b16cb374225107513/codehighlighter/python/highlight.py#L93

That no module is found.

**Comment by jmzambon** [comment]
You're right, thank you for pointing that.

**Comment by baseplate-admin** [comment]
Hi thanks for addressing this quickly.

Perhaps one message would be better? Because i think it would be better for future debugging.

**Comment by jmzambon** [comment]
Hi,

To be sure: have you in mind a logged message or a popup one?
As with the last commit, once an exception is raised, a popup message will be automatically prompted by the program, while the same will also be logged.

**Comment by baseplate-admin** [comment]
Okay, i was thinking from purely logging standpoint. Imagine i plan on using a headless version of libreoffice. In that case, a custom logging message would be better, no?

**Comment by baseplate-admin** [comment]
With that being addressed. Thank you for your awesome work.

**Comment by jmzambon** [comment]
Done.
And, actually, I was wrong: there would be no automatic popup message on module import stage...
