### ISSUE TITLE
Readme needs to be updated. Highlighing happens in "Format" not in "Tools" menu.

### ISSUE THREAD

**Issue by Roland-Pfeiffer** [jmzambon/libreoffice-code-highlighter#3]
See title, basically. The readme states that the highlighting happens via "Tools", but it is only from the screenshots that it can be seen that that seems to have moved to "Format".

**Comment by jmzambon** [comment]
Fixed by [AVAtarMod](https://github.com/jmzambon/libreoffice-code-highlighter/issues?q=is%3Apr+author%3AAVAtarMod) (#4).
Thank again.
