### ISSUE TITLE
Use some expanded sections for options instead of More button

### ISSUE THREAD

**Issue by kompilainenn** [jmzambon/libreoffice-code-highlighter#33]
Button 'More...' is not UX friendly for me.
Better if options 'Add line numbering' and 'Use character styles' could have expanded section bottom with its option.
Here is a mock-up about my idea:
![image](https://github.com/user-attachments/assets/1b6dc056-df9c-497d-a3a8-ed5589e77439)

**Comment by jmzambon** [comment]
Hi,

Thank you for the suggestion and for the mock-up.
It would be fine but, if I'm not wrong, there is in LibreOffice dialog api no widget for such expandable control. This doesn't mean it can't be done, but it's more hard work.
I pin your issue and hope to have soon some more time to develop this.

**Comment by jmzambon** [comment]
Actually easier to implement that expected.
As always, your comments are welcome!

**Comment by kompilainenn** [comment]
> As always, your comments are welcome!

I just shocked! You are a monster of coding!
It works as I expected, very well and very good job!
Thank you!
Closed as Fixed

**Comment by jmzambon** [comment]
Coding needs good ideas. Thanks for yours.
