### ISSUE TITLE
won't install on Portable LibreOffice v24.8.2.1

### ISSUE THREAD

**Issue by monkeymoong** [jmzambon/libreoffice-code-highlighter#47]
hi
the extension won't install on Portable LibreOffice 24.8.2.1 ???
it seems to be ok with the installed version

**Comment by jmzambon** [comment]
Hi,

Do you mean the Windows portable version available here : https://www.libreoffice.org/download/portable-versions?
What is the error message exactly?
(Don't have a Windows PC right now...)

**Comment by monkeymoong** [comment]
yes it is this portable version
the error is :
Extension Manager:
\\?\D:\0001-Applications_portables\DOC0-App.Libre.Office\App\libreoffice\program\..\program\..\..\..\Data\settings\user\extensions\tmp\extensions\lu14424fd2si.tmp_\codehighlighter2 (1).oxt\python\pythonpath\pygments\lexers\__pycache__\ezhil.cpython-38.pyc n'existe pas.

**Comment by jmzambon** [comment]
I've just made a test on a Windows 11 machine, with LibreOffice Portable 24.8.2.1: install works without any complain!
The strange thing is that the package should be located at "_\<user\>\uno_packages\cache\uno_packages\lu14424fd2si.tmp\_\codehighlighter2.oxt_", while your LibreOffice is searching the extension in "_\<user\>\extensions\tmp\extensions\..._", which is not correct I think.
How did you install the extension?

**Comment by monkeymoong** [comment]
i've made a fresh install on Windows 11 of LibreOffice Portable 24.8.2.1, 
the extension come from [https://extensions.libreoffice.org/](url)
i installed it with "Tools/Extensions..."
![Capture d'écran 2024-11-12 200451](https://github.com/user-attachments/assets/c905a150-2495-42f0-8c1f-f1397925eb06)

**Comment by monkeymoong** [comment]
it seems that i found the error
i had a space in my installation path
i made a fresh install on C: without any space and it's ok now...
thanks

**Comment by jmzambon** [comment]
Thanks for your feedback. A space in the install path should not be an issue, and the installation works on my PC with a path test with spaces...
Anyway, I'm happy you find your solution ;-) .

**Comment by monkeymoong** [comment]
You're right, the pb seems to come from the path length ? if i reduce the length of the path to LibreOfficePortable.exe 
i can now install and uninstall extensions without error messages...

"C:\Users\Marc LG\Downloads\LibreOfficePortable\LibreOfficeWriterPortable.exe" (78 characters)  ---> i can't install

"C:\Users\Marc LG\Downloads\LibreOff\LibreOfficePortable.exe" (67 characters) ---> i can install and uninstall 

could it be the reason ?

**Comment by jmzambon** [comment]
Hi,

This could be. I've experienced a couple of times such problems on Windows PC.
Enjoy your LibreOffice experience! ;-)
