### ISSUE TITLE
Missing R language Option

### ISSUE THREAD

**Issue by Byron-Ding** [jmzambon/libreoffice-code-highlighter#48]
![image](https://github.com/user-attachments/assets/6f8beb56-c42d-4d39-81a7-9f1d17a58f0a)

https://www.r-project.org/

**Comment by jmzambon** [comment]
Please read the... [README](https://github.com/jmzambon/libreoffice-code-highlighter/blob/master/README.md#tips) (second tip). This is a Pygments choice, see here: https://pygments.org/demo.

As stated in the README, typing R will be accepted and will be mapped to S language.

**Comment by Byron-Ding** [comment]
> 请阅读...[README](https://github.com/jmzambon/libreoffice-code-highlighter/blob/master/README.md#tips)（第二个提示）。这是 Pygments 的选择，请参阅此处：https://pygments.org/demo。
> 
> 如 README 中所述，键入 R 将被接受，并将被映射到 S 语言。

Thanks a lot for help and offering the website. It solves my Problem.
Suggestion: Maybe to add https://pygments.org/demo into the ReadMe file will help people to check whether their using language is actually support.
