### ISSUE TITLE
Still a problem with disappearing numbers

### ISSUE THREAD

**Issue by nerdcraft-muc** [jmzambon/libreoffice-code-highlighter#50]
When highligthing the following ruby code

`
6.times {puts create_name(4,12)}`

The "6" disappers.

**Comment by jmzambon** [comment]
Hi,

Have you installed the last version available on github? 
Using it I do not reproduce...

**Comment by nerdcraft-muc** [comment]
Oh, sorry no - I used the LO updater ...

**Comment by nerdcraft-muc** [comment]
Yes, it is fixed! Thanks again.
