### ISSUE TITLE
Spanish translation for Code Highlighter 2

### ISSUE THREAD

**Issue by Bantoniof** [jmzambon/libreoffice-code-highlighter#53]
I have created/edited the files for the Spanish translation of CodeHighlighter 2
I tried to look for your email but I couldn't find it anywhere.
Tell me where to send the files if you want to include the Spanish translation
- I'm new to Github and I don't know how to make a pull request

**Comment by jmzambon** [comment]
Hi,

Thank you very much!
I've restored my email on the [info page](https://github.com/jmzambon).
Just send me your work and I'll merge it (with credit of course :) ).
