### ISSUE TITLE
LibreOffice Basic Code Style

### ISSUE THREAD

**Issue by flywire** [jmzambon/libreoffice-code-highlighter#6]
It looks like there is no style to match lo basic and a new style is needed:
* https://github.com/LibreOffice/core/blob/master/basic/source/comp/token.cxx#L35-L177 and https://github.com/LibreOffice/core/blob/master/basic/source/comp/exprgen.cxx#L38-L61
* https://pygments.org/docs/lexerdevelopment/

**Comment by jmzambon** [comment]
Hi,

Thank you for the relevant source files.
I would be happy to try to suggest specific lexer and style, as soon as I have some free time.

**Comment by flywire** [comment]
The following file is probably good enough for the styles folder as described in: https://pygments.org/docs/styledevelopment/

**star.py**
```py
from pygments.style import Style
from pygments.token import Keyword, Name, Comment, String, Error, \
     Number, Operator, Generic

class StarStyle(Style):
    default_style = ""
    styles = {
        Comment:                '#808080',   # Gray
        Keyword:                '#0000FF',   # Blue
        Name:                   '#008000',   # Green
        Name.Function:          '#008000',   # Green
        Name.Class:             '#008000',   # Green
        String:                 '#FF0000'    # Red
    }
```

**Comment by flywire** [comment]
Work in Progress: StarOfficeBasic Lexer - [basic.py](https://github.com/jmzambon/libreoffice-code-highlighter/files/8986479/basic.py.txt).

Very simple model just using keywords should reflect LO IDE colors. More differentiation could be done later.

**Comment by jmzambon** [comment]
Just in case:
- https://github.com/LibreOffice/core/blob/master/svtools/source/config/colorcfg.cxx#L447-L453
- https://github.com/LibreOffice/core/blob/e4a57dcdabc9ae7d381025e008b90635c1b7b10c/include/tools/color.hxx#L448

**Comment by flywire** [comment]
VbNetLexer is good enough. Need alias for LibreOfficeBasic, OpenOfficeBasic and StarOfficeBasic, maybe lobas, oobas and sobas.

**Comment by flywire** [comment]
I don't know how to implement the lexer solution but something like one of these two options should work:

1. Modify [dotnet.py](https://github.com/jmzambon/libreoffice-code-highlighter/blob/master/codehighlighter/python/pythonpath/pygments/lexers/dotnet.py#L387-L394)

```diff
 class VbNetLexer(RegexLexer):
     """
     For Visual Basic.NET source code.
+    Also LibreOffice Basic, OpenOffice Basic, and StarOffice Basic.
     """
 
     name = 'VB.net'
     url = 'https://docs.microsoft.com/en-us/dotnet/visual-basic/'
-    aliases = ['vb.net', 'vbnet']
+    aliases = ['vb.net', 'vbnet', 'lobas', 'oobas', 'sobas']
```

2. **starofficebasic.py** - New lexer calling another (but I don't know how)

```py
from pygments.lexer import VbNetLexer
from pygments.token import *

class StarOfficeBasicLexer(VbNetLexer):
    name = 'sobas'
    aliases = ['oobas', 'lobas']

    def get_tokens_unprocessed(self, text):
        for index, token, value in VbNetLexer.get_tokens_unprocessed(self, text):
            yield index, token, value
```
