### ISSUE TITLE
Change Code Style in LibreOffice Writer without Rerunning Pygments

### ISSUE THREAD

**Issue by flywire** [jmzambon/libreoffice-code-highlighter#8]
Changing a style is an easy way to update a document without reprocessing the whole document. This is especially an issue with mixed coding language documents.

The [office:automatic-styles](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part3-schema/OpenDocument-v1.3-os-part3-schema.html#__RefHeading__1415058_253892949) are not accessible in the LibreOffice user interface. Pygments can support a css stylesheet.

Options:
* the css stylesheet should be user-accessible to support style updates across the document
* a LibreOffice [formatter](https://pygments.org/docs/formatterdevelopment/) could be written

**Comment by jmzambon** [comment]
Hi,

I've pushed a [new branch](/jmzambon/libreoffice-code-highlighter/tree/styleoption) for testing an option which allows to use character styles in Writer, when possible.

FYI, character styles are not available in text shapes and non-text modules (Calc, Impress...).

The option is available from the codehighlighter dialog. Could you install the oxt file of that branch and try it?

**Comment by flywire** [comment]
Yes, it works nicely: [codeTest23a.odt](https://github.com/jmzambon/libreoffice-code-highlighter/files/8986717/codeTest23a.odt)

![image](https://user-images.githubusercontent.com/11288701/175816053-3d402ab5-f4df-4a1b-bc91-0c20042a0200.png)

It looks like one [office:automatic-styles](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part3-schema/OpenDocument-v1.3-os-part3-schema.html#__RefHeading__1415058_253892949) is slipping through:

```html
    ><office:automatic-styles
        ><style:style
            style:name="P1"
            style:family="paragraph"
            style:parent-style-name="Preformatted_20_Text"
            ><style:text-properties fo:language="zxx"
            fo:country="none"/></style:style
        ></office:automatic-styles
```

A few things come to mind:
1. User could change the style so `ch2_DefaultStyle` prefix isn't appropriate, suggest user configurable with `code` default.
2. Use existing styles in document, don't overwrite.
3. A massive number of styles are generated, document users will probably define a more manageable style set and need to know how to load it.
4. Is it possible to suppress unused styles?

---

Can you comment on making a css sheet accessible?

**Comment by jmzambon** [comment]
> It looks like one [office:automatic-styles](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part3-schema/OpenDocument-v1.3-os-part3-schema.html#__RefHeading__1415058_253892949) is slipping through:

This has nothing to do with Code Highlighter. The xml is entirely generated by LIbreOffice. 

> A few things come to mind:
> 1. User could change the style so `ch2_DefaultStyle` prefix isn't appropriate, suggest user configurable with `code` default.

I don't understand what you mean.
 
> 2. Use existing styles in document, don't overwrite.

IMHO this is not a good idea : why should Code Highlighter use a specific template styles, among hundreds of others?, and what if a document contains more than one style to highlight code snippets?
 
> 3. A massive number of styles are generated, document users will probably define a more manageable style set and need to know how to load it.
> 4. Is it possible to suppress unused styles?

~~Need more work. I'll see~~. Done.
 
> Can you comment on making a css sheet accessible?

Please read this about css: https://pygments.org/docs/styledevelopment.

**Comment by flywire** [comment]
> Done.

Nicer still.

---

I'd like to push the points in this section through until we reach consensus.

> > 1. User could change the style so `ch2_DefaultStyle` prefix isn't appropriate, suggest user configurable with `code` default.
> 
> I don't understand what you mean.

A style is applied to an element, eg Heading1..9. The element name does not contain the style sheet name.

`[Code].Keyword` is an element created by CH2 (defined in the lexer). A separate process applies the defined style to that element. If a different style sheet is applied to the document, the element name in the styles list shouldn't change, just look different.

The style name should not be included in the list of styles, which are elements. (There is an exception below for multiple styles for same element in document.)

> > 2. Use existing styles in document, don't overwrite.
> 
> IMHO this is not a good idea : why should Code Highlighter use a specific template styles, among hundreds of others?

The ability for users to manage styles in Writer is the fundamental reason for exposing the styles as user-changeable.

Code snippets can exist in paragraphs or in-line text. If the user selects the `Code` character style (and selects it as the parent style in CH2)  then CH2 should use it rather than overwriting the element style with a new parent style (clobbering it). If user selected parent style doesn't exist then create it (default `Code` if one style for one element ).

With a known parent style name, a big benefit is a master template can be used to update the styles across many documents.

> and what if a document contains more than one style to highlight code snippets?

Good point. Normally (default) there would be one style for one element (eg Keyword) but there may be cases where different styles are needed for the same element type in same document (_not_ one style for one element type).

---

> Please read this about css: https://pygments.org/docs/styledevelopment.

I did for https://github.com/jmzambon/libreoffice-code-highlighter/issues/6#issuecomment-1166296086 but it's not relevant.

It's demonstrated [here](https://overiq.com/pygments-tutorial/#highlighting-code):
> If open `out.html` in a browser you will find that code doesn't appear to be highlighted at all. This is because by default `HtmlFormatter` generates HTML with CSS classes to marks various tokens, but it doesn't generate the actual CSS styles. We will see how to fix this in the next section.

I'm suggesting [perhaps] the CSS stylesheet could be user-accessible. The reality is any changes to the applied style are likely to be simple, something like turning off italics in comments. The styles aren't accessible in LO apps other than Writer, and simple changes might be more easily made in a CSS stylesheet.

![image](https://user-images.githubusercontent.com/11288701/175838960-c0e87796-a484-4ff7-bb54-d24d67839205.png)

**Comment by jmzambon** [comment]
#### About style naming
It  seems more consistent with Pygments to keep the name of the style in the character style naming. I could of course use token keywords only,  but this will prevent the simultaneous use of different styles, which would be an unfortunate limitation. 
We need a better idea here...

By the way, you mention a `code` style that does not exist by default, but is specific to the template you use.

#### About css
LibreOffice does not use css for style management. Could you explain more specifically how you think css can help here?

**Comment by flywire** [comment]
> I could of course use token keywords only, but this will prevent the simultaneous use of different styles

Yes, as a user-selectable option, off by default, would work very well and simplify using a single code style.

Maybe `Disable multiple pygments styles` option to drop the default parent style names and enable a box with `Parent style name:` `Code` (default).

> you mention a `Code` style that does not exist by default, but is specific to the template you use.

![image](https://user-images.githubusercontent.com/11288701/176051885-378ef2fe-ffcd-472c-a36c-1ff992653c6c.png)

![image](https://user-images.githubusercontent.com/11288701/176051915-19005b1b-9d63-4c02-85f3-d7f2fe0265d4.png)

I expect most formal documents would use a template with a code type style.

Instead of creating `ch2_DefaultStyle` as the parent, use (or create) `Code` character style as parent to ensure all document style attributes not set by Pygments are inherited. Detail in first point.

**Comment by flywire** [comment]
I'd like to test with #9 if it is ready to merge.

**Comment by jmzambon** [comment]
> Yes, as a user-selectable option, off by default, would work very well and simplify using a single code style.
> 
> Maybe `Disable multiple pygments styles` option to drop the default parent style names and enable a box with `Parent style name:` `Code` (default).

I'll have a look at this... after my holidays!

 
> > you mention a `Code` style that does not exist by default, but is specific to the template you use.
> 
> [image](https://user-images.githubusercontent.com/11288701/176051885-378ef2fe-ffcd-472c-a36c-1ff992653c6c.png)
> 
> [image](https://user-images.githubusercontent.com/11288701/176051915-19005b1b-9d63-4c02-85f3-d7f2fe0265d4.png)

They are in fact custom styles from the LO chapter template. All users don't have it and still should be able to use whatever paragraph style they want for code formatting.



> I expect most formal documents would use a template with a code type style.

An extension should be useable for all users, event those who prefer their own paragraph style, or even no style at all.


 
> Instead of creating `ch2_DefaultStyle` as the parent, use (or create) `Code` character style as parent to ensure all document style attributes not set by Pygments are inherited. Detail in first point.

See response details above.



> I'd like to test with https://github.com/jmzambon/libreoffice-code-highlighter/pull/9 if it is ready to merge.

It is not ready as it is. See comment in the pull request thread.

**Comment by flywire** [comment]
I don't see your last comments conflicting with mine. I'm thinking default `Disable multiple Pygments style sets` would be simpler for the beginner.

---

Similar Sample Document: [codeTest23Demo.odt](https://github.com/jmzambon/libreoffice-code-highlighter/files/9010867/codeTest23Demo.odt)

I've renamed and relinked the styles into the type of thing a technical writer could be comfortable with. The document is not behaving well. The child styles should only contain color where required and the background has now disappeared. If you take Character Style _Keyword_, pressing _Reset to Parent_ doesn't clear _Contains_.

![image](https://user-images.githubusercontent.com/11288701/176437717-5f480fa9-85dc-41c5-a087-95ddd5a0f8b0.png)

I set _Name.Function_ to bold as a test.

**Comment by jmzambon** [comment]
As said already, 
> I'll have a look at this... after my holidays!

**Comment by jmzambon** [comment]
I still see two caveats with your proposal:
- once created, the styles will not change (overwriting them at each call of Code Highlighter would make no sense); in this case, the user will no more be able to change the style, except by switching back to direct formatting; he might even think that the programme is no longer working properly;
- style names such as _Name_, _Keyword_, _Text_, _Punctuation_... are too generic and could easily conflict with styles already defined by the user.

**Comment by flywire** [comment]
* User defined styles:
  * Master template will overwrite styles
  * Issue is user created styles in document (the purpose of a template), `UserDefinedStyles` default off
* I agree must use dot notation to avoid conflicting names

---

I've been testing the attached hack: [highlight.py](https://github.com/jmzambon/libreoffice-code-highlighter/files/9020691/highlight.py.txt) (unfortunately I just merged your last 3 commits before uploading it). Doesn't support renaming `parent_style = "Code"`, `UserDefinedStyles`, or gui changes.

[original_highlight.py](https://github.com/jmzambon/libreoffice-code-highlighter/files/9020808/original_highlight.py.txt)

**Comment by flywire** [comment]
My current understanding of configuration and functionality comments using indicative terms.

1. lexer - always applied

2. `UseCharStyles`
* False [default] - hard-coded styles from macro, nothing below applies
* True - use Writer character style interface

---

3. `BaseParent` = Code [default] - User definable name inherited by all character code styles

   a. `UseMultiStyles` = False [default??], seems easier for users to understand
    ```
    CodeParent = BaseParent
    
    Code
     Code.Literal
      Code.Literal.Number
      Code.Literal.String
      ...
    ```

   b. `UseMultiStyles` = True
    ```
    CodeParent = [Named]Style
    
    Code
     DefaultStyle
      DefaultStyle.Literal
       DefaultStyle.Literal.Number
       DefaultStyle.Literal.String
       ...
     libreoffice-classicStyle
      libreoffice-classicStyle.Literal
       libreoffice-classicStyle.Literal.Number
       libreoffice-classicStyle.Literal.String
       ...
    ```

4. `UserDefinedStyles`
* False [default] - running ch2 will redefine all styles (for NamedStyle) except BaseParent
* True - only define new styles

**Comment by jmzambon** [comment]
I'm still not convinced. Nevertheless I've implemented that in the _styleoption_ branch. The option is available from the _More..._ button.

Please test and keep me informed.

**Comment by flywire** [comment]
This is getting pretty close, it looks nice and it is simple:

1. Styles can be changed and update to CH2 styles correctly
2. All prefix styles are inherited by CH2 except CH2 styles (only tested font color) including background color
3. Set background color, seems to be a paragraph area, regardless of on/off setting it always clears background of Custom prefix style - seems to be wrong.

---

See previous comment about `UserDefinedStyles`, essentially expectation is styles assigned in document will be used (otherwise they are fixed format):

1. Expectation of a defined prefix style being used currently fails due to:
    a. CH2 style is applied to prefix style, changes style of in-line snippets (see last point). **This is the key issue (including background)
    b. CH2 style overwrites prefix style descendent styles
    c. background removed from prefix style
2. Reasonable to assume if code block area color is required with  `UserDefinedStyles` it will be applied with paragraph styles using same background color as prefix style
3. Default style is a recent feature which conflicts with previous proposal (and Pygments ??)
    a. If document has no style defined, CH2 should apply one, inheriting from prefix style
    b. prefix style can't support a default for CH2 style
4. It fails on in-line snippets, highlighting whole paragraph. eg Highlight Print in: A sentence might discuss `Print` in basic.

---

Options (with Custom prefix: `Code`):
![image](https://user-images.githubusercontent.com/11288701/177552965-048cd719-0072-4a46-b257-df6bba33d08a.png)

Template (note background and colors are lighter than next image):
![image](https://user-images.githubusercontent.com/11288701/177552622-988754ff-c83e-494b-9d42-9343031a2554.png)

Document showing prefix style background lost and all template styles are ignored:
![image](https://user-images.githubusercontent.com/11288701/177552715-4b67e7ae-e8c8-4ba3-b238-ac3dfd7cd9c9.png)

Code:
```bas
Sub ExampleForNextSort
    Dim iEntry(10) As Integer
    Dim iOuter As Integer, iInner As Integer, iTemp As Integer
    Dim bSomethingChanged As Boolean

    ' Fill the array with integers between -10 and 10
    For iOuter = LBound(iEntry()) To Ubound(iEntry())
        iEntry(iOuter) = Int((20 * Rnd) -10)
    Next iOuter

    ' iOuter runs from the highest item to the lowest
    For iOuter = UBound(iEntry()) To LBound(iEntry()) Step -1
        'Assume that the array is already sorted and see if this is incorrect
        bSomethingChanged = False
        For iInner = LBound(iEntry()) To iOuter-1
            If iEntry(iInner) > iEntry(iInner+1) Then
                iTemp = iEntry(iInner)
                iEntry(iInner) = iEntry(iInner+1)
                iEntry(iInner+1) = iTemp
                bSomethingChanged = True
            End If
        Next iInner
        'If the array is already sorted then stop looping!
        If Not bSomethingChanged Then Exit For
    Next iOuter

    Dim s$
    For iOuter = LBound(iEntry()) To Ubound(iEntry())
        s = s & iOuter & " : " & iEntry(iOuter) & CHR$(10)
    Next iOuter
    MsgBox s, 0, "Sorted Array"
End Sub
```
[Code2.ott.zip](https://github.com/jmzambon/libreoffice-code-highlighter/files/9129802/Code2.ott.zip)

**Comment by jmzambon** [comment]
>     3. Set background color, seems to be a paragraph area, regardless of on/off setting it always clears background of Custom prefix style - seems to be wrong.

Yes, it is a paragraph area (or shape area or frame area...). When selected, the option add the background associated with de style if any. Otherwise it clears background.

> See previous comment about `UserDefinedStyles`, essentially expectation is styles assigned in document will be used (otherwise they are fixed format):
> 
>     1. Expectation of a defined prefix style being used currently fails due to:
>        a. CH2 style is applied to prefix style, changes style of in-line snippets (see last point). **This is the key issue (including background)
>        b. CH2 style overwrites prefix style descendent styles
>        c. background removed from prefix style

Sorry, this is very unclear.

>     2. Reasonable to assume if code block area color is required with  `UserDefinedStyles` it will be applied with paragraph styles using same background color as prefix style

This requires some thought.

>     3. Default style is a recent feature which conflicts with previous proposal (and Pygments ??)
>        a. If document has no style defined, CH2 should apply one, inheriting from prefix style
>        b. prefix style can't support a default for CH2 style

This will break CH2 main feature, which is to highlight code according to the selected code style. This requires to (re)define the styles accordingly.  Or my understanding of your request is not right.

>     4. It fails on in-line snippets, highlighting whole paragraph. eg Highlight Print in: A sentence might discuss `Print` in basic.

Yes, this is the expected behaviour (see README file). We may of course discuss it.

> Document showing prefix style background lost and all template styles are ignored: [image](https://user-images.githubusercontent.com/11288701/177552715-4b67e7ae-e8c8-4ba3-b238-ac3dfd7cd9c9.png)

See above about breaking CH2 main feature.

**Comment by jmzambon** [comment]
I'm wondering: what you want, in other words, is CH2 to just apply the lexer but no internal style? 

If so, what about an entry in the style combo box, let's say "Custom style", that will apply an existing LibO character style?

**Comment by flywire** [comment]
> what do you want, main feature (and this is unclear)

Document styles (ie `UserDefinedStyles`) should override CH2 style.
1. Run lexer
2. apply style:
    a. document style
    b. where style not defined, CH2 style

Once a style is applied to a document, CH2 would use it. If a new style occurs (eg _Error_) and user doesn't like it they can change the document (or template) style.

---

Default style is a very good feature but it is still an issue. ~I understand is an extension of Pygments.~ CH2 must not change prefix style. [Maybe use `default_style = '#000080', # Blue`](https://github.com/jmzambon/libreoffice-code-highlighter/commit/0427cce057ad21f9d4a315fd281f00a6a7f1708e#r77880508)

---

> [when background not selected] it clears background.

It shouldn't, it is overwriting paragraph style.

> [paragraph style] requires some thought

Don't over-think it. Paragraphs control things like spacing before/after, margins, and _area fill_. Character styles will overwrite paragraph styles so background for paragraph and character styles should match or it will look strange. This is up to the user, not CH2.

**Comment by flywire** [comment]
> CH2 must not change prefix style [or predefined styles].

As of CH V2.3.3 this is the only problem for documents using predefined styles. The option `Use character styles in Writer` could also be understood as: _if the style is defined in Writer, use it_. It is reasonable for users that might use a template.

`token style` is being used as a default style. The implementation becomes don't apply the `token style` to the custom prefix, apply it to all styles under the custom prefix unless they have another defined style, either in Writer or CH2.

---

I can see `addstyle` is an iterative function that progresses to the parent but I'm not clear how the code works or how to enable logging.

**Comment by jmzambon** [comment]
> I'm not clear [...] how to enable logging.

Go to *Tools -> Options -> Advanced -> Open Expert Configuration*. Search for `ooo.ext.code-highlighter.Registry -> Settings` and change the value of `LogLevel` to 1 (INFO) or 2 (DEBUG).

If you want the log to be saved in a file, set `LogToFile` to 1: the log will be outputted to the user's LibreOffice profile with the name *codehighlighter.log*.

**Comment by jmzambon** [comment]
Fixed from https://github.com/jmzambon/libreoffice-code-highlighter/commit/304d8f24a03e2345db96c6cbb1eec197484b8a9b.
